#!/bin/sh /etc/rc.common

USE_PROCD=1
START=97
STOP=10

FIKA_GW_BIN="/usr/bin/fika_iot_gateway"
FIKA_GW_CONFIG="/etc/fika_iot_gateway/fika_iot_gateway.yaml"
FIKA_GW_PID="/var/run/fika_iot_gateway.pid"
FIKA_GW_DATA="/var/lib/fika_iot_gateway"

start_service() {
	mkdir -p "$FIKA_GW_DATA"
	procd_open_instance fika_iot_gateway
	procd_set_param command "$FIKA_GW_BIN" "$FIKA_GW_CONFIG"
	procd_close_instance
}
