#!/bin/sh
#
# start redis
#

start() {
	#. /lib/functions/network.sh
	#network_get_ipaddrs myLanIp guest
	printf "Starting fika-opennds: "
	umask 077
	start-stop-daemon -S -q -c root:root -b \
		-x /usr/bin/opennds -- \
                -c /etc/opennds/longdong.conf

	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping fika-opennds: "
	killall -KILL opennds
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
