[package]
name = "aws-iot-device-sdk-rust"
description = "An easy to use SDK for connecting to AWS IoT Core."
documentation = "https://docs.rs/aws-iot-device-sdk-rust"
repository = "https://github.com/arnstein/aws-iot-device-sdk-rust"
license = "MIT"
version = "0.1.2"
authors = ["Arnstein Kleven <arnsteinkleven@gmail.com>"]
edition = "2021"

include = [
    "src/lib.rs",
    "src/client.rs",
    "src/error.rs",
    "Cargo.toml",
    "README.md"
    ]


[features]
default = ["async"]
async = ["tokio"]

[dependencies]
rumqttc = "0.15.0"
serde_json = "1.0"
mqtt4bytes = "0.4.0"
tokio = { version = "1.19.2", features = ["rt-multi-thread", "sync", "macros", "net", "time"], optional = true }
