[core]
database = "redis://127.0.0.1:6379"
version = "0.1.0"
thirdparty = "longdong2"

[[subscribe]]
topic = "kdaemon.easy.setup"
path = "/etc/fika_manager/easy_setup.sh"

[[subscribe]]
topic = "kdaemon.por.config"
path = "/etc/fika_manager/por_config.sh"

[[subscribe]]
topic = "captive-portal"
path = "/etc/fika_manager/captive-portal.sh"

[[subscribe]]
topic = "cmp/remote-manage"
path = "/etc/fika_manager/remote_manage.sh"

[[subscribe]]
topic = "cmp/pairing"
path = "/etc/fika_manager/cmp_pairing.sh"

[[task]]
topic = "nms.shadow.update.provision"
start_at = {secs = 3, nanos = 0 }
path = "/etc/fika_manager/provision.sh"
db_publish = true

[[task]]
topic = "nms.shadow.update.heartbeat"
period = {secs = 600, nanos = 0 }
path = "/etc/fika_manager/heartbeat.sh"
db_publish = true

[[task]]
topic = "nms.shadow.update.runtime-statistics"
start_at = {secs = 30, nanos = 0 }
period = {secs = 600, nanos = 0 }
path = "/etc/fika_manager/runtime_statistics.sh"
db_publish = true

[[task]]
topic = "nms.shadow.update.maker"
start_at = {secs = 10, nanos = 0 }
path = "/etc/fika_manager/maker.sh"
db_publish = true

[[task]]
topic = "kdaemon.system.checking"
start_at = {secs = 1, nanos = 0 }
period = {secs = 180, nanos = 0 }
path = "/etc/fika_manager/system_checking.sh"
db_set = true
