[core]
database = "redis://127.0.0.1:6379"
version = "0.1.0"

[[subscribe]]
topic = "easy-setup"
path = "/etc/fika_manager/easy_setup.sh"

[[subscribe]]
topic = "captive-portal"
path = "/etc/fika_manager/captive-portal.sh"

[[subscribe]]
topic = "cmp/remote-manage"
path = "/etc/fika_manager/remote_manage.sh"

[[publish]]
topic = "provision"
start_at = {secs = 1, nanos = 0 }
path = "/etc/fika_manager/provision.sh"

[[publish]]
topic = "heartbeat"
period = {secs = 600, nanos = 0 }
path = "/etc/fika_manager/heartbeat.sh"

[[publish]]
topic = "runtime-statistics"
start_at = {secs = 10, nanos = 0 }
period = {secs = 600, nanos = 0 }
path = "/etc/fika_manager/runtime_statistics.sh"

[[publish]]
topic = "maker"
start_at = {secs = 10, nanos = 0 }
path = "/etc/fika_manager/maker.sh"
