[core]
pre="/etc/fika_manager/factory/pre_core.sh"
post="/etc/fika_manager/factory/post_core.sh"
key = "kap.core"
[core.cfg]
wallet_address = "change-me"
database_url = "redis://127.0.0.1:6379"

[network]
post="/etc/fika_manager/factory/post_wifi_ssid_by_uci.sh"
key = "kdaemon.easy.setup"
[network.cfg]
wan_type = 0
wan_username = "change-me"
wan_password = "change-me"
wifi_ssid = "K-Private"
wifi_password = "change-me"
password_overwrite = "on"

[por]
key = "kap.por.config"
[por.cfg]
state = false
nickname = "change-me"

[boss]
post="/etc/fika_manager/factory/post_boss.sh"
key = "kap.boss"
[boss.cfg]
root_url = "https://oss-api.k36588.info"
access_token = "ce18d7a0940719a00da82448b38c90b2"
otp_path = "v0/ap/otp"
ap_token_path = "v0/ap/ap_token"
hcs_path = "v0/hcs/pair"

[cmp]
post="/etc/fika_manager/factory/post_cmp.sh"
key = "kap.cmp"
[cmp.cfg]
endpoint = "a1v9khdje2rkn9-ats.iot.us-east-1.amazonaws.com"
port = 8883
thing = "longdongThing1"
cert = "/etc/fika_iot_gateway/e749408131b357ef9e051f31ffe661540480ff7269fe88f62bc86bc1e4020787-certificate.pem.crt"
key = "/etc/fika_iot_gateway/e749408131b357ef9e051f31ffe661540480ff7269fe88f62bc86bc1e4020787-private.pem.key"
ca = "/etc/fika_iot_gateway/AmazonRootCA1.pem"
